- hosts: all
  become: yes
  user: ubuntu
  gather_facts: no
  pre_tasks:
    - name: Atualizando o Repo
      raw: "apt-get update" ## Utilizado para pré task
    - name: Instalando o Python
      raw: "apt-get install -y python"
  roles:
    - { role: install-k8s, tags: ["install_k8s_role"] }

- hosts: k8s_master
  become: yes
  user: ubuntu
  roles:
    - { role: create_cluster, tags: ["create_cluster_role"] }

- hosts: k8s_workers
  become: yes
  user: ubuntu
  roles:
    - { role: join-workers, tags: ["join_workers_role"] }

- hosts: k8s_master
  become: yes
  user: ubuntu
  roles:
    - { role: install-helm, tags: ["install_helm_role"] }

- hosts: k8s_master
  become: yes
  user: ubuntu
  roles:
    - { role: install_monit_tools, tags: ["install_monit-tools_role"] }
