---
- name: Get Helm Install
  get_url:
    url: "{{ helm_url }}"
    dest: "{{ tmp_get_helm }}"
    mode: 0775
#  ignore_errors: true
  register: get_helm

- name: Install Helm on Kubernetes
  shell:
    "{{ tmp_get_helm }}"
  when:
    - get_helm.failed | bool == false
  register: install_helm

- name:
  debug: var=install_helm      
